<?xml version="1.0" encoding="UTF-8"?>
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.damap</groupId>
  <artifactId>base</artifactId>
  <version>0.0.0-SNAPSHOT</version>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>A tool for machine actionable DMPs.</description>
  <url>https://github.com/damap-org/damap-backend</url>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>http://www.opensource.org/licenses/mit-license.php</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Valentin Futterer</name>
      <email>valentin.futterer@tuwien.ac.at</email>
      <organization>Vienna University of Technology</organization>
      <organizationUrl>https://www.tuwien.at/</organizationUrl>
    </developer>
    <developer>
      <name>Laura Thaci</name>
      <email>lthaci@tugraz.at</email>
      <organization>Graz University of Technology</organization>
      <organizationUrl>https://www.tugraz.at/</organizationUrl>
    </developer>
  </developers>

  <scm>
    <url>https://maven.pkg.github.com/damap-org/damap-backend</url>
    <connection>scm:git:https://github.com/damap-org/damap-backend.git</connection>
    <developerConnection>scm:git:https://github.com/damap-org/damap-backend.git</developerConnection>
  </scm>

  <properties>
    <surefire-plugin.version>3.2.3</surefire-plugin.version>
    <maven.compiler.target>17</maven.compiler.target>
    <maven.compiler.source>17</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <compiler-plugin.version>3.12.1</compiler-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>3.11.1</quarkus.platform.version>
    <sonar.version>3.9.0.2155</sonar.version>
    <spotless.version>2.44.0.BETA1</spotless.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- Test -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jacoco</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-component</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-mockito</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-security</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-security-jwt</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-h2</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock</groupId>
      <artifactId>wiremock</artifactId>
      <version>3.13.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-validator</artifactId>
    </dependency>
    <!-- Rest -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jaxb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
    </dependency>
    <!-- Authentication -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-jwt</artifactId>
    </dependency>
    <!-- Database -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-envers</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-oracle</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-liquibase</artifactId>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
    </dependency>
    <!-- Health -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <!-- Utility -->
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>0.10.2</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.30</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>5.4.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>5.4.0</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-core</artifactId>
      <version>3.2.3</version>
    </dependency>
    <dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-parsers-standard-package</artifactId>
      <version>3.2.3</version>
    </dependency>
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
    </dependency>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>2.2.34</version>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.6</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.14.0</version>
        <executions>
          <execution>
            <id>commonstandard</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>src/main/resources/org/damap/base/dmpcommonstandard/openapi.yaml</inputSpec>
              <generatorName>java</generatorName>
              <output>${project.build.directory}/generated-sources/rda-dmp-common-standard</output>
              <generateApis>false</generateApis>
              <openapiNormalizer>KEEP_ONLY_FIRST_ONEOF=true,SIMPLIFY_ONEOF_ANYOF=true,REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true</openapiNormalizer>
              <schemaMappings>
                <schemaMapping>Contributor_contributor_id=ContributorID</schemaMapping>
                <schemaMapping>Contact_contact_id=ContactID</schemaMapping>
                <schemaMapping>Creator_creator_id=ContributorID</schemaMapping>
                <schemaMapping>Metadata_metadata_standard_id=MetadataStandardID</schemaMapping>
                <schemaMapping>Project_project_id=ProjectID</schemaMapping>
              </schemaMappings>
              <importMappings>
                <importMapping>Affiliation=org.damap.base.rda.dmpcommonstandard.Affiliation</importMapping>
                <importMapping>ContributorID=org.damap.base.rda.dmpcommonstandard.ContributorID</importMapping>
                <importMapping>ContactID=org.damap.base.rda.dmpcommonstandard.ContactID</importMapping>
                <importMapping>DatasetID=org.damap.base.rda.dmpcommonstandard.DatasetID</importMapping>
                <importMapping>FunderID=org.damap.base.rda.dmpcommonstandard.FunderID</importMapping>
                <importMapping>GrantID=org.damap.base.rda.dmpcommonstandard.GrantID</importMapping>
                <importMapping>Identifier=org.damap.base.rda.dmpcommonstandard.Identifier</importMapping>
                <importMapping>DMPID=org.damap.base.rda.dmpcommonstandard.DMPID</importMapping>
              </importMappings>
              <configOptions>
                <useOneOfInterfaces>false</useOneOfInterfaces>
                <useComposedSchema>false</useComposedSchema>
                <addOneOfInterfaceImports>true</addOneOfInterfaceImports>
                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                <sourceFolder>src/java/main</sourceFolder>
                <useJakartaEe>true</useJakartaEe>
                <library>native</library>
                <useBeanValidation>true</useBeanValidation>
                <additionalModelTypeAnnotations>
                  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY);
                  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                </additionalModelTypeAnnotations>
                <serializationLibrary>jackson</serializationLibrary>
                <dateLibrary>java8</dateLibrary>
                <annotationLibrary>none</annotationLibrary>
                <apiPackage>org.damap.base.rda.dmpcommonstandard</apiPackage>
                <modelPackage>org.damap.base.rda.dmpcommonstandard</modelPackage>
                <invokerPackage>org.damap.base.rda.dmpcommonstandard</invokerPackage>
                <configKey>rest-integration</configKey>
                <artifactUrl>https://github.com/RDA-DMP-Common</artifactUrl>
                <groupId>org.damap</groupId>
                <artifactId>rda-dmp-common-standard</artifactId>
                <artifactVersion>1.0.0</artifactVersion>
                <artifactDescription>Auto-generated sources for the DAMAP integration for the RDA DMP Common Standard</artifactDescription>
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>client</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>src/main/resources/org/damap/base/integration/generic/openapi.yaml</inputSpec>
              <generatorName>java</generatorName>
              <output>${project.build.directory}/generated-sources/integration-generic</output>

              <!-- This is needed to make the ProjectWithID inherit from Project properly: -->
              <openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true,KEEP_ONLY_FIRST_ONEOF=true,SIMPLIFY_ONEOF_ANYOF=true,REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true</openapiNormalizer>

              <!--region Name mappings -->
              <!--
              The following mappings reuse the objects generated in the execution above for the purposes of the client.
              -->
              <schemaMappings>
                <schemaMapping>Project=org.damap.base.rda.dmpcommonstandard.Project</schemaMapping>
                <schemaMapping>Funding=org.damap.base.rda.dmpcommonstandard.Funding</schemaMapping>
                <schemaMapping>Contributor=org.damap.base.rda.dmpcommonstandard.Contributor</schemaMapping>
                <schemaMapping>Contact=org.damap.base.rda.dmpcommonstandard.Contact</schemaMapping>
                <schemaMapping>Dataset=org.damap.base.rda.dmpcommonstandard.Dataset</schemaMapping>
                <schemaMapping>Cost=org.damap.base.rda.dmpcommonstandard.Cost</schemaMapping>

                <schemaMapping>Affiliation=org.damap.base.rda.dmpcommonstandard.Affiliation</schemaMapping>
                <schemaMapping>ContributorID=org.damap.base.rda.dmpcommonstandard.ContributorID</schemaMapping>
                <schemaMapping>ContactID=org.damap.base.rda.dmpcommonstandard.ContactID</schemaMapping>
                <schemaMapping>ProjectID=org.damap.base.rda.dmpcommonstandard.ProjectID</schemaMapping>
                <schemaMapping>DatasetID=org.damap.base.rda.dmpcommonstandard.DatasetID</schemaMapping>
                <schemaMapping>FunderID=org.damap.base.rda.dmpcommonstandard.FunderID</schemaMapping>
                <schemaMapping>GrantID=org.damap.base.rda.dmpcommonstandard.GrantID</schemaMapping>
                <schemaMapping>DMPID=org.damap.base.rda.dmpcommonstandard.DMPID</schemaMapping>
                <schemaMapping>Identifier=org.damap.base.rda.dmpcommonstandard.Identifier</schemaMapping>

                <!-- Internal Normalizer Fixes -->
                <schemaMapping>Contributor_contributor_id=org.damap.base.rda.dmpcommonstandard.ContributorID</schemaMapping>
                <schemaMapping>Contact_contact_id=org.damap.base.rda.dmpcommonstandard.ContactID</schemaMapping>
                <schemaMapping>Creator_creator_id=org.damap.base.rda.dmpcommonstandard.ContributorID</schemaMapping>
                <schemaMapping>Metadata_metadata_standard_id=org.damap.base.rda.dmpcommonstandard.MetadataStandardID</schemaMapping>

              </schemaMappings>
              <importMappings>
                <importMapping>ProjectID=org.damap.base.rda.dmpcommonstandard.ProjectID</importMapping>
              </importMappings>
              <!--
              The following mappings are needed because the OpenAPI generator ignores the object names from an
              externally referenced OpenAPI schema and generates arbitrary names for them:
              -->
              <inlineSchemaNameMappings>
                <inlineSchemaNameMappings>The_DMP_Project_Funding_Items_Schema=Funding</inlineSchemaNameMappings>
                <inlineSchemaNameMappings>The_Contributor_ID_Schema=ContributorID</inlineSchemaNameMappings>
                <inlineSchemaNameMappings>The_Contributor_Items_Schema=Contributor</inlineSchemaNameMappings>
                <inlineSchemaNameMappings>The_Funder_ID_Schema=FunderID</inlineSchemaNameMappings>
                <inlineSchemaNameMappings>The_Funding_Grant_ID_Schema=GrantID</inlineSchemaNameMappings>
                <inlineSchemaNameMapping>The_Contact_ID_Schema=ContactID</inlineSchemaNameMapping>
                <inlineSchemaNameMapping>The_DMP_Contact_Schema=Contact</inlineSchemaNameMapping>
              </inlineSchemaNameMappings>
              <!--endregion-->

              <configOptions>
                <useOneOfInterfaces>false</useOneOfInterfaces>
                <useComposedSchema>false</useComposedSchema>
                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                <sourceFolder>src/java/main</sourceFolder>
                <useJakartaEe>true</useJakartaEe>
                <library>native</library>
                <useBeanValidation>true</useBeanValidation>
                <additionalModelTypeAnnotations>
                  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY);
                  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                </additionalModelTypeAnnotations>
                <serializationLibrary>jackson</serializationLibrary>
                <dateLibrary>java8</dateLibrary>
                <annotationLibrary>none</annotationLibrary>
                <apiPackage>org.damap.base.integration.generic</apiPackage>
                <modelPackage>org.damap.base.integration.generic</modelPackage>
                <invokerPackage>org.damap.base.integration.generic</invokerPackage>
                <configKey>generic-integration</configKey>
                <artifactUrl>https://damap.org/manual/cris/</artifactUrl>
                <groupId>org.damap.integration</groupId>
                <artifactId>generic</artifactId>
                <artifactVersion>1.0.0</artifactVersion>
                <artifactDescription>Auto-generated sources for the DAMAP REST API for CRIS integration using the RDA DMP Common Standard</artifactDescription>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.7.0</version>
        <executions>
          <execution>
            <id>attach-javadocs-verify</id>
            <phase>verify</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <parameters>${maven.compiler.parameters}</parameters>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemProperties>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemProperties>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>jaxb2-maven-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <id>xjc</id>
            <goals>
              <goal>xjc</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <sources>
            <source>src/main/resources/org/damap/base/spec/re3data/re3dataV3-0.xsd</source>
            <source>src/main/resources/org/damap/base/spec/re3data/re3dataV2-2.xsd</source>
            <source>src/main/resources/org/damap/base/spec/re3data/re3data_index_V1-0.xsd</source>
            <source>src/main/resources/org/damap/base/spec/oaf/oaf-response-1.0.xsd</source>
          </sources>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>3.1.2</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jsonschema2pojo</groupId>
        <artifactId>jsonschema2pojo-maven-plugin</artifactId>
        <version>1.1.1</version>
        <configuration>
          <annotationStyle>jackson</annotationStyle>
          <sourceDirectory>${basedir}/src/main/resources/org/damap/base/schema</sourceDirectory>
          <targetPackage>org.damap.base.rest.madmp.dto</targetPackage>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>${spotless.version}</version>
        <configuration>
          <java>
            <!-- These are the defaults, you can override if you want -->
            <includes>
              <include>src/main/java/**/*.java</include>
              <include>src/test/java/**/*.java</include>
            </includes>

            <!-- Cleanthat will refactor your code, but it may break your style: apply it before
            your formatter -->
            <cleanthat />
            <googleJavaFormat></googleJavaFormat>
            <importOrder /> <!-- standard import order -->
            <removeUnusedImports /> <!-- self-explanatory -->
            <formatAnnotations />  <!-- fixes formatting of type annotations -->
          </java>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>verify</phase>
          </execution>
        </executions>
      </plugin>
      <!-- Add liquibase commands -->
      <plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>4.28.0</version>
      </plugin>
      <!-- Index resources for this package. When setting this package as a dependency, it will automatically
      register all beans and resources and the endpoints are available.
      -->
      <plugin>
        <groupId>io.smallrye</groupId>
        <artifactId>jandex-maven-plugin</artifactId>
        <version>3.1.8</version>
        <executions>
          <execution>
            <id>make-index</id>
            <goals>
              <goal>jandex</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Generate <package>-sources.jar for deployment -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.3.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>
                      ${project.build.directory}/${project.build.finalName}-runner
                    </native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.native.enabled>true</quarkus.native.enabled>
        <quarkus.package.jar.enabled>false</quarkus.package.jar.enabled>
      </properties>
    </profile>

    <profile>
      <id>sonar</id>
      <properties>
        <sonar.projectKey>damap-org_damap-backend</sonar.projectKey>
        <sonar.coverage.jacoco.xmlReportPaths>
          ${project.build.directory}/jacoco-report/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.sonarsource.scanner.maven</groupId>
            <artifactId>sonar-maven-plugin</artifactId>
            <version>${sonar.version}</version>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>deploy-github-repository</id>
      <distributionManagement>
        <repository>
          <id>github</id>
          <name>GitHub</name>
          <url>https://maven.pkg.github.com/damap-org/damap-backend</url>
        </repository>
      </distributionManagement>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.2.4</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
                <configuration>
                  <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                  </gpgArguments>
                  <passphraseServerId/>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>deploy-mvn-repository</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.2.4</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
                <configuration>
                  <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                  </gpgArguments>
                  <passphraseServerId/>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>0.8.0</version>
            <extensions>true</extensions>
            <configuration>
              <publishingServerId>central</publishingServerId>
              <autoPublish>true</autoPublish>
              <waitUntil>published</waitUntil>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
