# custom config settings
# replace these in the config of your custom project or by overriding these variables
damap:
  # TODO: Move under tenant-aware
  generic-cris-api-key: 'api-key-here'
  env: DEV # override in your custom project with PROD for production deployment
  auth:
    # Scopes to request during login:
    scope: openid profile email offline_access microprofile-jwt roles personID
    # The OIDC claim path that will hold your DAMAP roles in the access token
    user-roles-claim-path: realm_access/roles
    # The OIDC claim to use as a user ID:
    user-id-claim: personID
    # The OIDC claim that holds the users full name
    name-claim: name
    # The OIDC claim that holds the users given name
    given-name-claim: given_name
    # The OIDC claim that holds the users family name
    family-name-claim: family_name
    # The OIDC claim that holds the users email
    email-claim: email
    # The OIDC claim that holds the users affiliations
    affiliations-claim: affiliation
    # Role name used to identify DAMAP super admins
    # If DAMAP is locally deployed ADMIN_ROLE constant in the DefaultProfile test profile needs to be
    # the same as here, otherwise the tests fail
    admin-role-name: Damap Admin

  # tenant-aware here means that in case of multitenancy, these configs need to be set per tenant, and not per instance
  # for more information, see the multitenancy documentation on the website
  tenant-aware:
    title: DAMAP Tool

    fields:
      ethical-report-enabled: true

    project-service: default
    ## Elsevier Pure integration:
    # project-service: elsevier-pure
    # The following settings map Pure classification URIs to DAMAP properties. Pure classification URIs start with
    # /dk/atira/pure, but are otherwise specific to the institutional setup in Pure.

    # The project description field DAMAP should use:
    elsevier-pure-description-classification: /dk/atira/pure/projectdescription
    # How Pure project contributor classifications map to DAMAP:
    elsevier-pure-contributor-role-classifications:
      # DAMAP supports the following roles:
      # DATA_COLLECTOR, DATA_CURATOR, DATA_MANAGER, DISTRIBUTOR, EDITOR, HOSTING_INSTITUTION, PRODUCER, PROJECT_LEADER,
      # PROJECT_MANAGER, PROJECT_MEMBER, REGISTRATION_AGENCY, REGISTRATION_AUTHORITY, RELATED_PERSON, RESEARCHER,
      # RESEARCH_GROUP, RIGHTS_HOLDER, SPONSOR, SUPERVISOR, WORK_PACKAGE_LEADER, PRINCIPAL_INVESTIGATOR,
      # PROJECT_COORDINATOR, OTHER
      - pure-role-uri: /dk/atira/pure/member
        contributor-role: PROJECT_MEMBER
    # Which Pure classification should be read as the project lead:
    elsevier-pure-project-lead-role-classification: /dk/atira/pure/projectlead
    ## HTTP backend:
    elsevier-pure-backend: http
    elsevier-pure-endpoint-url: "https://your-pure-instance.elsevierpure.com/ws/api"
    elsevier-pure-api-key: "your API key here"
    ## Alternatively, the file-based backend:
    # elsevier-pure-backend: file
    elsevier-pure-projects-file: "file:///path/to/projects.json"
    elsevier-pure-persons-file: "file:///path/to/persons.json"

    ## Set up person lookups here:
    person-services:
      ## Elsevier Pure integration:
      # - display-text: "Pure"
      #   query-value: "PURE"
      #   class-name: "org.damap.base.integration.pure.PurePersonService"
      - display-text: "University"
        query-value: "UNIVERSITY"
        class-name: "org.damap.base.integration.mock.MockUniversityPersonServiceImpl"
      - display-text: "ORCID"
        query-value: "ORCID"
        class-name: "org.damap.base.integration.orcid.ORCIDPersonServiceImpl"

invenio:
  disabled: true
  shared-secret: "thisIsAVerySecretKeyOfAtLeast32Chars"

# general config settings
quarkus:
  http:
    cors:
      ~: true
      origins: http://localhost:8085
      headers: origin,content-type,accept,authorization
      access-control-max-age: 1
    # needed for the file analysis endpoint. Specify how large a single file for upload may be.
    limits:
      max-body-size: 10M

  oidc:
    auth-server-url: http://keycloak:8080/realms/damap
    client-id: damap
    token:
      issuer: http://localhost:8087/realms/damap
    roles:
      role-claim-path: ${damap.auth.user-roles-claim-path}

  datasource:
    jdbc:
      url: jdbc:postgresql://damap-db:5432/damap
      driver: org.postgresql.Driver
    db-kind: postgresql
    username: damap
    password: pw4damap

  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: none
    sql-load-script: no-file

  cache:
    caffeine:
      "repositories":
        expire-after-write: P1D
      "repository":
        expire-after-write: P1D
      "user-sync-cache":
        initial-capacity: 100
        maximum-size: 1000
        expire-after-write: 12H
      "pure-recommended":
        expire-after-write: 1H
      "pure-search-projects":
        expire-after-write: 1H
      "pure-read-project":
        expire-after-write: 1H
      "pure-read-person":
        expire-after-write: 1H
      "pure-search-persons":
        expire-after-write: 1H

  liquibase:
    migrate-at-start: true
    change-log: org/damap/base/db/changeLog-root.yaml

  smallrye-openapi:
    info-title: DAMAP API

  swagger-ui:
    always-include: true # set to false if swagger-ui should only be available in dev mode
    oauth-client-id: ${quarkus.oidc.client-id}

rest:
  generic-cris/mp-rest/url: http://localhost:8888/
  mock-projects/mp-rest/url: http://api-mock:80
  mock-persons/mp-rest/url: http://api-mock:80
  gotenberg/mp-rest/url: http://gotenberg:3000
  r3data:
    repositories/mp-rest/url: https://www.re3data.org/api
    repositories/mp-rest/scope: jakarta.inject.Singleton
  openaire/mp-rest/url: https://api.openaire.eu
  orcid:
    search/mp-rest/url: https://pub.orcid.org
  # Leaving this URL empty will deactivate the feature in the frontend
  # Right now this feature is experimental, to test it use the value https://ostrails-dmp-evaluation.arisnet.ac.at
  # TODO: Make this compatible with multitenancy and add a specific on and off switch
  # Maybe move it into the db so admins can configure this?
  evaluation/mp-rest/url:

"%dev":
  damap:
    title: "DAMAP (Development)"

  quarkus:
    http:
      cors:
        origins: http://localhost:4200

    oidc:
      auth-server-url: http://localhost:8087/realms/damap
      token:
        issuer: http://localhost:8087/realms/damap

    # FOR ORACLE INSTEAD USE:
    #      url: jdbc:oracle:thin:@localhost:8088/FREEPDB1
    #      driver: oracle-driver
    #      db-kind: oracle.jdbc.OracleDriver
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:8088/damap
        driver: org.postgresql.Driver
      db-kind: postgresql
      username: damap
      password: pw4damap

  rest:
    gotenberg/mp-rest/url: http://localhost:3000
    mock-projects/mp-rest/url: http://localhost:8091
    mock-persons/mp-rest/url: http://localhost:8091

"%test":
  damap:
    title: "DAMAP (Testing)"
    repositories:
      recommendation: ["r3d100010468"] # Re3Data id(s)
    elsevier-pure-endpoint-url: "http://localhost:9999/fake-pure-api"
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
        url: jdbc:h2:mem:test
    oidc:
      enabled: false

"%multitenant":
  quarkus:
    datasource:
      active: false # deactivate unnamed default datasource
      bootstrap: # the same as deactivated default datasource, but with a name, needed for CustomTenantResolver
        jdbc:
          url: ${quarkus.datasource.jdbc.url}
          driver: ${quarkus.datasource.jdbc.driver}
        db-kind: ${quarkus.datasource.db-kind}
        username: ${quarkus.datasource.username}
        password: ${quarkus.datasource.password}

    liquibase:
      bootstrap:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml

    hibernate-orm:
      datasource: bootstrap # hibernate needs a bootstrap db to build the persistence unit - its later unused
      sql-load-script: no-file
      schema-management:
        strategy: none
      multitenant: DATABASE

    config:
      # should point to a (out of classpath) config file like this /path/to/config/file.yaml
      # TODO: currently hardcoded - add env variable to make path configurable
      locations: /opt/damap/tenants.yaml
