pipelines:
  openshift:
    stages:
      build:
        variants:
          - name: oracle
            latest: true
            args:
              BUILD_PROFILE: oracle
          - name: postgres
            args:
              BUILD_PROFILE: postgres
      deploy:
        enabled: false
  maven:
    imageTag: jdk-17
    stages:
      publish:
        enabled: false

whenBranch:
  next:
    pipelines:
      maven:
        stages:
          publish:
            enabled: true
    post:
      success:
        trigger: [ "CSD/damap-tuw-be/next" ]
  master:
    pipelines:
      maven:
        stages:
          publish:
            enabled: true
