/**
  * This file is a Jenkins pipeline definition in Groovy which is supposed to be run
  * on CSD servers with specific requirements, thus this file might be useless for anyone
  * outside of CSD repositories.
  *
  * This pipeline definition is based on a Jenkins shared library 'ops-jenkins-library'
  * for which you can find code and documentation under https://git.tiss.tuwien.ac.at/CSD/ops-jenkins-lib
  **/

@Library('ops-jenkins-library@next') _

csdPipeline()
