name: Maven pipeline

on:
  #push:
  pull_request:
    branches:
      - master
      - next
  workflow_dispatch:

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.2' ]
        java: [ '11' ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

      - name: Build with Maven
        run: mvn -B install

      - name: Publish to GitHub packages
        run: mvn -B -Pgithub -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
