name: Release pipeline

on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

jobs:
  maven-test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '11'
          maven-version: '3.8.2'

      - name: Build with Maven
        run: mvn -B install

      - name: Publish to GitHub packages
        run: mvn -B -Pgithub -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: minddocdev/docker-publish-action@master
        with:
          name: tuwien-csd/damap-backend/damap-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
