name: Release pipeline

on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

jobs:
  maven-test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11.0.2
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0

      - name: Publish to GitHub packages
        run: mvn -B -Pgithub deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish to Registry
        uses: minddocdev/docker-publish-action@master
        with:
          name: tuwien-csd/damap-backend/damap-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
