on:
  workflow_run:
    workflows: [test]
    types:
      - completed

jobs:
  on-success:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }} # checkout commit that triggered this workflow
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '11'
          maven-version: '3.8.2'

      - name: Run Sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -Psonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=tuwien-csd
          -Dsonar.projectKey=tuwien-csd_damap-backend
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.coverage.exclusions=docker/**/*,
          sonar:sonar